/* Review-only session shell. No clinical inputs or recorded treatment content. */
(()=>{
const phases=[['قبل ما نبدأ','التعارف وخطة الجلسة','شرح نطاق الجلسة وما يلزم مراجعته قبل استخدامها.'],['نجهّز المساحة','التحضير','شرح التحكّم والتوقف والتحضير قبل الانتقال.'],['نحدّد نقطة البداية','التقييم','مكان فيديو التقييم وإرشادات سائد؛ المحتوى السريري لم يُضف بعد.'],['وقت المتابعة','المعالجة','مكان توجيه سائد قبل كل مجموعة، ثم شاشة الكرة والصوت.'],['نراجع المعنى','التثبيت','مكان فيديو مراجعة المعنى الإيجابي مع سائد.'],['ننتبه للجسم','مسح الجسم','مكان توجيه سائد لمراجعة الاستجابة الجسدية.'],['نختم بهدوء','الإغلاق','مكان فيديو الإغلاق، مع مسار خاص عند التوقف المبكر.'],['نرجع نراجع','إعادة التقييم','مرحلة لاحقة لمراجعة ما تغيّر؛ ليست استمرارًا تلقائيًا بنفس الجلسة.']];
let step=0,mode='both',volume=.12,pace=1400,ctx,raf=0,running=false,start=0,lastBeat=-1,early=false,active=new Set(),generation=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stop(){generation++;running=false;cancelAnimationFrame(raf);active.forEach(n=>{try{n.stop()}catch{}});active.clear();const b=document.querySelector('#stim-start');if(b)b.disabled=false;const status=document.querySelector('#stim-status');if(status)status.textContent='متوقف';}
window.stopSessionMedia=stop;
function beep(pan){if(!ctx||ctx.state!=='running')return;const o=ctx.createOscillator(),g=ctx.createGain(),p=ctx.createStereoPanner();o.type='sine';o.frequency.value=440;p.pan.value=pan;const t=ctx.currentTime;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.12);o.connect(g).connect(p).connect(ctx.destination);active.add(o);o.onended=()=>{active.delete(o);o.disconnect();g.disconnect();p.disconnect()};o.start();o.stop(t+.14);}
async function audioReady(){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('unsupported');ctx??=new C();await ctx.resume();if(ctx.state!=='running')throw Error('blocked');}
function settings(){return `<div class="session-settings"><label>طريقة المتابعة<select id="stim-mode"><option value="both" ${mode==='both'?'selected':''}>كرة وصوت</option><option value="visual" ${mode==='visual'?'selected':''}>كرة فقط</option><option value="audio" ${mode==='audio'?'selected':''}>صوت فقط</option></select></label><label>سرعة العرض<select id="stim-pace"><option value="1400" ${pace===1400?'selected':''}>هادئة</option><option value="1000" ${pace===1000?'selected':''}>متوسطة</option></select></label><label>مستوى الصوت<input id="stim-volume" aria-label="مستوى الصوت" type="range" min="0" max="0.3" step="0.01" value="${volume}"></label></div><p class="session-help">للصوت المتناوب: استخدم سماعات ستيريو وافحص الجهتين. هذه تجربة تقنية لمدة 12 ثانية.</p><div class="actions"><button class="secondary" data-session="left">اختبار اليسار</button><button class="secondary" data-session="right">اختبار اليمين</button></div>`}
window.sessionScreen=()=>{const p=phases[step];return `<div class="session-head"><a class="back" href="#/">رجوع للرئيسية</a><button class="secondary" data-session="exit">أوقف وأنتقل للإغلاق</button></div><div class="eyebrow">نموذج EMDR للمراجعة · ${step+1} / 8</div><h1>${p[0]}</h1><p class="session-disclaimer">استعراض للواجهة ببيانات افتراضية، وليس جلسة علاج جاهزة للاستخدام. لا تستحضر ذكرى مؤلمة لتجربته.</p><div class="session-steps" aria-label="مراحل الجلسة">${phases.map((x,i)=>`<button data-stage="${i}" ${i===step?'aria-current="step"':''}><span>${i+1}</span>${x[1]}</button>`).join('')}</div><div class="guide-placeholder"><img src="assets/saed-reflection.png" alt="سائد دزدار"/><div><span class="eyebrow">فيديو سائد · ${p[1]}</span><h2>${step===6&&early?'نختم بعد التوقف':p[0]}</h2><p>${p[2]}</p><small>الفيديو لم يُسجّل بعد</small><button class="secondary" data-session="replay">مكان إعادة الشرح</button></div></div>${step===1||step===3?`${settings()}<div class="stim-field" aria-label="مساحة متابعة الحركة"><div id="stim-ball" ${mode==='audio'?'hidden':''}></div><span id="audio-label" ${mode!=='audio'?'hidden':''}>استمع للتناوب بين الجهتين</span></div><div class="stim-controls"><button class="primary" id="stim-start" data-session="start">جرّب الحركة والصوت</button><button class="secondary" data-session="stop">توقّف</button><span id="stim-status" role="status" aria-live="polite">متوقف</span></div>`:''}${step===3?'<div class="actions"><button class="secondary" data-session="again">أعيد مشاهدة التوجيه</button><button class="secondary" data-session="exit">بدي أوقف وأختم</button></div>':''}${step===6?`<div class="detail-note"><h3>${early?'مسار التوقف المبكر':'نهاية تجربة المراحل'}</h3><p>هنا يظهر فيديو الإغلاق المناسب، دون افتراض اكتمال المعالجة.</p></div>`:''}${step===7?'<div class="detail-note"><h3>مراجعة في وقت لاحق</h3><p>مكان فيديو المتابعة. لا يصدر النموذج تقييمًا أو قرارًا علاجيًا.</p></div>':''}<div class="session-bottom"><button class="secondary" data-session="prev" ${step===0?'disabled':''}>المرحلة السابقة</button><button class="secondary" data-session="wait">بدي وقت</button><button class="primary" data-session="next">${step===7?'أنهي الاستعراض':step===6?'استعرض المتابعة اللاحقة':'جاهز أكمل الاستعراض'}</button></div>`};
function redraw(){window.stopSessionMedia();render();}
async function run(){stop();const ticket=generation;try{if(mode!=='visual')await audioReady();if(ticket!==generation)return;running=true;start=performance.now();lastBeat=-1;document.querySelector('#stim-start').disabled=true;const ball=document.querySelector('#stim-ball'),field=document.querySelector('.stim-field'),status=document.querySelector('#stim-status');function tick(now){if(!running)return;const dt=now-start;if(dt>=12000){stop();status.textContent='انتهت تجربة الـ12 ثانية';return;}const turn=dt/pace,pan=-Math.cos(Math.PI*turn);if(ball)ball.style.left=(50+pan*42)+'%';const beat=Math.floor(turn);if(beat!==lastBeat){lastBeat=beat;if(mode!=='visual')beep(beat%2===0?-1:1);}status.textContent=`${Math.ceil((12000-dt)/1000)} ثانية`;raf=requestAnimationFrame(tick);}raf=requestAnimationFrame(tick);}catch{stop();const s=document.querySelector('#stim-status');if(s)s.textContent='تعذّر تشغيل الصوت. جرّب مرة ثانية أو اختار كرة فقط.';}}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.stage!==undefined){step=Number(el.dataset.stage);early=false;redraw();return;}const a=el.dataset.session;if(!a)return;if(a==='start'){run();return;}stop();if(a==='left'||a==='right'){const ticket=generation;try{await audioReady();if(ticket===generation)beep(a==='left'?-1:1);}catch{toast('الصوت غير متاح في هذا المتصفح');}return;}if(a==='exit'){early=true;step=6;}else if(a==='next'){if(step===7){step=0;early=false;go('/');return;}step++;}else if(a==='prev')step=Math.max(0,step-1);else if(a==='wait'){toast('خُد وقتك. الحركة والصوت متوقفان.');return;}else if(a==='replay'||a==='again'){toast('فيديو التوجيه بانتظار التسجيل.');return;}else return;redraw();});
document.addEventListener('change',e=>{if(e.target.id==='stim-mode'){stop();mode=e.target.value;redraw();}if(e.target.id==='stim-pace'){stop();pace=Number(e.target.value);}});
document.addEventListener('input',e=>{if(e.target.id==='stim-volume')volume=Number(e.target.value)});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('pagehide',stop);window.addEventListener('hashchange',stop);
})();
